version: '3.9'

services:
    poi:
        image: ghcr.io/giannikoch/poi:main
        depends_on:
            - postgres
        volumes:
            - $POI_DATA:/var/lib/poi/data
        environment:
            - ConnectionStrings:PostgreSQL=$ConnectionStringsPostgreSQL
            - Discord:Prefix=$DiscordPrefix
            - Discord:Token=$DiscordToken
            - Paths:DataFolderPath=/var/lib/poi/data
    postgres:
        image: postgres:16-alpine
        ports:
            - 5001:5432
        volumes:
            - $POSTGRES_DATA:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_DB=$POSTGRES_DB